# Travis-CI Build for SimpleAmqpClient
# see travis-ci.org for details

language: cpp

os: linux
dist: xenial

jobs:
  include:
    - env: CC=gcc-7 CXX=g++-7 FLAGS=""
    - env: CC=clang-8 CXX=clang++-8 FLAGS=""
    - env: CC=clang-8 CXX=clang++-8 FLAGS="-g -O1 -fsanitize=address,undefined -fno-omit-frame-pointer"
    - env: CC=clang-8 CXX=clang++-8 FLAGS="-g -O1 -fsanitize=thread -fno-omit-frame-pointer"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-8
      - sourceline: deb http://dl.bintray.com/rabbitmq-erlang/debian xenial erlang
        key_url: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
      - sourceline: deb https://dl.bintray.com/rabbitmq/debian xenial main
        key_url: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
    packages:
      - gcc-7
      - g++-7
      - clang-8
      - libboost-dev
      - libboost-chrono-dev
      - libboost-system-dev
      - rabbitmq-server
      - ninja-build

# install pre-reqs
install:
  - mkdir -p _prereqs
  - pushd _prereqs
  - git clone https://github.com/alanxz/rabbitmq-c
  - cd rabbitmq-c
  - git checkout v0.10.0
  - export RABBITMQC_DIR=`pwd`/../../_install
  - cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${RABBITMQC_DIR} -DBUILD_EXAMPLES=OFF -DBUILD_TESTS=OFF -DBUILD_TOOLS=OFF .
  - cmake --build . --target install
  - popd

before_script:
  - mkdir _build
  - cd _build
  - pwd

# Run the Build script
script:
  - cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-Wall -Wextra -Werror ${FLAGS}" -DCMAKE_INSTALL_PREFIX=../_install -DENABLE_TESTING=ON -DRabbitmqc_DIR=${RABBITMQ_C_DIR} ..
  - cmake --build . --target install
  - AMQP_BROKER=localhost ASAN_OPTIONS=detect_leaks=1 ctest -V .
